version: "2"

volumes:
  mysql-data:
    driver: local
  dot-caddy:
    driver: local
  backups:
    driver: local

networks:
  rancher:

services:

  rancher:
    image: rancher/server
    container_name: rancher
    restart: always
    volumes:
      - "mysql-data:/var/lib/mysql"
      - "backups:/backups"
    networks:
      - rancher
    ports:
      - "11080:8080"
    logging:
      driver: journald

  caddy:
    image: abiosoft/caddy
    container_name: caddy
    restart: always
    volumes:
      - "dot-caddy:/root/.caddy"
      - "./Caddyfile:/etc/Caddyfile"
      - "backups:/backups"
    environment:
      - CADDY_VHOST=${VHOST}
      - CADDY_EMAIL=${EMAIL}
    networks:
      - rancher
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: journald
